---
name: Build and Push Assets on PR Merged

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --ignore-platform-reqs
          npm i

      - name: Build assets using Vite
        run: npm run build

      - name: Fix code styling
        run: composer format

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git add -f public/build
          git commit -m "Build assets using Vite, fix code styling"
          git push --force https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git main
        env:
          PAT: ${{ secrets.PAT }}
